import { addDays } from 'date-fns';
import type { GrowthExperiment, LaunchTask } from '../types';

const todayISO = () => new Date().toISOString();
const dueIn = (days: number) => addDays(new Date(), days).toISOString().slice(0, 10);

export const buildLaunchTasks = (): LaunchTask[] => [
  {
    id: 'ship-onboarding-polish',
    title: 'Polish onboarding tour highlights for first-time users',
    category: 'Ship',
    priority: 'High',
    status: 'todo',
    dueDate: dueIn(3),
    notes: 'Focus on tour step clarity + Finish action.',
    createdAtISO: todayISO(),
  },
  {
    id: 'ship-training-qa',
    title: 'QA Training plans + sessions on mobile',
    category: 'Ship',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(5),
    notes: 'Test adding sessions + plan completion flow.',
    createdAtISO: todayISO(),
  },
  {
    id: 'ship-reminder-edge-cases',
    title: 'Verify reminders + calendar edge cases (timezones)',
    category: 'Ship',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(7),
    notes: 'Check daylight savings + morning reminders.',
    createdAtISO: todayISO(),
  },
  {
    id: 'ship-feed-empty-states',
    title: 'Review empty-state copy for pets/feed/journal',
    category: 'Ship',
    priority: 'Low',
    status: 'todo',
    createdAtISO: todayISO(),
  },
  {
    id: 'analytics-onboarding',
    title: 'Track onboarding completion + skip events',
    category: 'Analytics',
    priority: 'High',
    status: 'todo',
    dueDate: dueIn(4),
    notes: 'Capture funnel: intro viewed → tour started → completed.',
    createdAtISO: todayISO(),
  },
  {
    id: 'analytics-training-plan',
    title: 'Add event for training plan start + day completion',
    category: 'Analytics',
    priority: 'Medium',
    status: 'todo',
    notes: 'Key KPI: % of users completing 3+ days.',
    createdAtISO: todayISO(),
  },
  {
    id: 'pwa-install-test',
    title: 'Test PWA install prompt on iOS + Android',
    category: 'App Store/PWA',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(6),
    notes: 'Capture screenshots for share page.',
    createdAtISO: todayISO(),
  },
  {
    id: 'pwa-manifest-review',
    title: 'Review manifest + icons for brand consistency',
    category: 'App Store/PWA',
    priority: 'Low',
    status: 'todo',
    createdAtISO: todayISO(),
  },
  {
    id: 'content-launch-posts',
    title: 'Draft 3 launch posts (training, reminders, pets)',
    category: 'Content',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(7),
    notes: 'Include 15s product demo clip.',
    createdAtISO: todayISO(),
  },
  {
    id: 'content-demo-video',
    title: 'Record 30s demo: calendar + reminders flow',
    category: 'Content',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(8),
    createdAtISO: todayISO(),
  },
  {
    id: 'outbound-beta-invites',
    title: 'Invite 20 dog owners to try MVP',
    category: 'Outbound',
    priority: 'High',
    status: 'todo',
    notes: 'Target people who log daily walks.',
    createdAtISO: todayISO(),
  },
  {
    id: 'outbound-trainers',
    title: 'Send 10 personal DMs to local trainers',
    category: 'Outbound',
    priority: 'Medium',
    status: 'todo',
    createdAtISO: todayISO(),
  },
  {
    id: 'community-facebook',
    title: 'Post launch note in local dog Facebook groups',
    category: 'Community',
    priority: 'Medium',
    status: 'todo',
    dueDate: dueIn(9),
    createdAtISO: todayISO(),
  },
  {
    id: 'community-feedback-form',
    title: 'Create feedback form and pin it in-app',
    category: 'Community',
    priority: 'Medium',
    status: 'todo',
    notes: 'Ask about favorite features + missing tools.',
    createdAtISO: todayISO(),
  },
  {
    id: 'partnerships-daycare',
    title: 'Reach out to 3 dog daycares for pilot partnership',
    category: 'Partnerships',
    priority: 'Medium',
    status: 'todo',
    createdAtISO: todayISO(),
  },
];

export const buildGrowthExperiments = (): GrowthExperiment[] => [
  {
    id: 'reels-training-plan',
    title: 'Instagram Reels: “Today’s Training” demo',
    hypothesis: 'Short product demos will drive profile visits and waitlist signups.',
    channel: 'Instagram Reels',
    audience: 'Dog owners who follow training content',
    message: 'Keep training consistent with a 2-minute plan overview.',
    kpi: '1000 plays, 3% profile click-through',
    status: 'running',
    startISO: todayISO(),
    notes: 'Post 3 variants (voiceover, captions, no audio).',
  },
  {
    id: 'tiktok-walk-like-pro',
    title: 'TikTok “Walk Like a Pro” before/after',
    hypothesis: 'Before/after clips will improve saves and shares.',
    channel: 'TikTok',
    audience: 'New dog parents, puppy owners',
    message: 'Show leash pulling → calm loose leash in 21 days.',
    kpi: '3000 views, 50 saves',
    status: 'idea',
  },
  {
    id: 'reddit-community-ama',
    title: 'Reddit AMA in r/dogs about training plans',
    hypothesis: 'Community Q&A will build trust and early signups.',
    channel: 'Reddit',
    audience: 'r/dogs and r/puppy101 members',
    message: 'Answer training consistency questions + share MVP.',
    kpi: '25 comments, 10 signups',
    status: 'idea',
  },
  {
    id: 'local-vet-flyer',
    title: 'Local vet flyer with QR to demo',
    hypothesis: 'Offline posters in vet clinics will drive local trials.',
    channel: 'Local partnerships',
    audience: 'Pet owners at vet visits',
    message: 'Try a free training plan + reminders for your dog.',
    kpi: '20 QR scans, 5 installs',
    status: 'idea',
  },
  {
    id: 'email-onboarding',
    title: 'Email onboarding sequence (3 emails)',
    hypothesis: 'Short onboarding emails increase plan starts.',
    channel: 'Email',
    audience: 'New signups in first week',
    message: 'Day 1: Training plan, Day 3: Reminders, Day 5: Journal.',
    kpi: '30% open rate, 15% plan start',
    status: 'running',
    startISO: todayISO(),
  },
  {
    id: 'trainer-shoutout',
    title: 'Partner trainer shoutout + demo plan',
    hypothesis: 'Trainer endorsements will drive high-intent installs.',
    channel: 'Partnerships',
    audience: 'Trainer followers',
    message: 'Track training wins with a simple plan + reminders.',
    kpi: '10 installs, 3 plan starts',
    status: 'idea',
  },
  {
    id: 'community-challenge',
    title: '7-day walk streak challenge',
    hypothesis: 'Short challenges increase repeat sessions.',
    channel: 'Community',
    audience: 'Existing users',
    message: 'Log 7 days, earn a badge + share your streak.',
    kpi: '25 participants, 50% completion',
    status: 'idea',
  },
  {
    id: 'inapp-share-prompt',
    title: 'In-app prompt to share training progress',
    hypothesis: 'Social sharing will bring new users through referrals.',
    channel: 'In-app',
    audience: 'Users completing Day 3 of a plan',
    message: 'Share your progress with friends.',
    kpi: '5 shares, 3 installs',
    status: 'idea',
  },
];
